# Hello World
A neural network is just a function that can learn patterns

In [1]:
from keras.layers import Dense
from keras import Sequential
model = Sequential(Dense(units=1, input_shape=[1]))

In [2]:
model.compile(optimizer="sgd", loss="mean_squared_error")

In [3]:
import numpy as np
x = np.arange(-10, 10)
x

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [4]:
y = 0.5 * x ** 2 + 10 * x - 5

In [5]:
model.fit(x, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 274ms/step - loss: 2590.3914
Epoch 2/500
1/1 [==============================] - 0s 2ms/step - loss: 591.6862
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 369.7390
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 341.2766
Epoch 5/500
1/1 [==============================] - 0s 2ms/step - loss: 334.0351
Epoch 6/500
1/1 [==============================] - 0s 989us/step - loss: 329.2650
Epoch 7/500
1/1 [==============================] - 0s 1ms/step - loss: 324.9204
Epoch 8/500
1/1 [==============================] - 0s 1000us/step - loss: 320.7725
Epoch 9/500
1/1 [==============================] - 0s 1ms/step - loss: 316.7903
Epoch 10/500
1/1 [==============================] - 0s 999us/step - loss: 312.9649
Epoch 11/500
1/1 [==============================] - 0s 2ms/step - loss: 309.2899
Epoch 12/500
1/1 [==============================] - 0s 2ms/step - loss: 305.7594
Epoch 13/500
1/1 [=========

In [7]:
model.predict([0])

array([[11.499483]], dtype=float32)

In [8]:
y[x==0]

array([-5.])

In [9]:
# GRADED FUNCTION: house_model
def house_model():
    ### START CODE HERE

    # Define input and output tensors with the values for houses with 1 up to 6 bedrooms
    # Hint: Remember to explictly set the dtype as float
    xs = np.arrange(1, 6)
    ys = 2*xs - 1

    # Define your model (should be a model with 1 dense layer and 1 unit)
    from keras import Sequential
    from keras.layers import Dense
    model = Sequential(Dense(units=10, input_shape=[1])

    # Compile your model
    # Set the optimizer to Stochastic Gradient Descent
    # and use Mean Squared Error as the loss function
    model.compile(optimizer="sgd", loss="mean_squared_error")

    # Train your model for 1000 epochs by feeding the i/o tensors
    model.fit(x, y, epochs=500)

    ### END CODE HERE
    return model

SyntaxError: invalid syntax (Temp/ipykernel_4360/3754139651.py, line 18)